---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-nifi-1"
    hostname: nifi-1.local
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: yes
    privileged: yes
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:8080:8080/tcp"
      - "0.0.0.0:8443:8443/tcp"
      - "0.0.0.0:2181:2181/tcp"
    networks:
      - name: local
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-nifi-2"
    hostname: nifi-2.local
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: yes
    privileged: yes
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:8081:8080/tcp"
      - "0.0.0.0:8444:8443/tcp"
      - "0.0.0.0:2182:2181/tcp"
    networks:
      - name: local
  - name: "${IMAGE:-rockylinux}-${TAG:-8}-nifi-3"
    hostname: nifi-3.local
    image: "${IMAGE:-rockylinux}:${TAG:-8}"
    pre_build_image: yes
    privileged: yes
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - "0.0.0.0:8082:8080/tcp"
      - "0.0.0.0:8445:8443/tcp"
      - "0.0.0.0:2183:2181/tcp"
    networks:
      - name: local
provisioner:
  name: ansible
  env:
    NIFI_VERSION: ${NIFI_VERSION:-1.15.3}
  inventory:
    host_vars:
      ${IMAGE:-rockylinux}-${TAG:-8}-nifi-1:
        nifi_zookeeper_id: 1
      ${IMAGE:-rockylinux}-${TAG:-8}-nifi-2:
        nifi_zookeeper_id: 2
      ${IMAGE:-rockylinux}-${TAG:-8}-nifi-3:
        nifi_zookeeper_id: 3
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint