on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.8, 3.9]
        nifi-version: [1.9.2, 1.10.0, 1.11.4, 1.12.1, 1.13.2, 1.14.0, 1.15.3]
        platform:
          - image: "centos"
            tag: "7"
          - image: "rockylinux"
            tag: "8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox
        env:
          ANSIBLE_FORCE_COLOR: '1'
          IMAGE: ${{ matrix.platform.image }}
          TAG: ${{ matrix.platform.tag }}
          NIFI_VERSION: ${{ matrix.nifi-version }}
